//01a_firstException.js
try {
    throw new Error('Gerando um erro gen√©rico!');
}
catch (e) {
    console.error(`${e.name}: ${e.message}`);
}